apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:20.04
    args:
    - sleep
    - infinity
    resources:
      requests:
        memory: "1G"
        cpu: 1
      limits:
        memory: "2G"
        cpu: 2
        